version: '3.8'

services:
  backend:
    build: ./BE
    container_name: cw_backend
    ports:
      - "3000:3000"
    volumes:
      - ./BE:/app
    environment:
      - NODE_ENV=development

  frontend:
    build: ./FE
    container_name: cw_frontend
    ports:
      - "8081:8081"
    volumes:
      - ./FE:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
